# Generated by Django 3.2.4 on 2021-12-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='default', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='default', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expirience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='default', max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='default', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.direction')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
                ('work', models.CharField(max_length=50, verbose_name='Место работы')),
                ('info', models.CharField(max_length=50, verbose_name='Дополнительная информация о себе')),
                ('employment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='polls.employment', verbose_name='Чем Вы сейчас занимаетесь')),
                ('expirience', models.ManyToManyField(blank=True, to='polls.Expirience', verbose_name='Программы')),
                ('language', models.ManyToManyField(blank=True, to='polls.Language', verbose_name='Языки программирования')),
                ('theme1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme1', to='polls.theme', verbose_name='Тема1')),
                ('theme2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme2', to='polls.theme', verbose_name='Тема2')),
                ('theme3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme3', to='polls.theme', verbose_name='Тема3')),
                ('theme4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme4', to='polls.theme', verbose_name='Тема4')),
            ],
        ),
    ]
